### ISSUE TITLE
box height on question-recipient target selection

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#114]
On question creation pages :: http://oglocal.herokuapp.com/ny/questions/new?type=Person

... sometimes the box heights vary for senators & reps, e.g. :: 

http://cl.ly/image/0z3K3Y2f1v0u

cc @walter - ideal is to display two senators next to each other on top row of two boxes, with US rep in box below on the left. 

Is this an issue for Walter, in terms of the length of the elected official names & titles? Realize it's a bit tricky.

**Comment by walter** [comment]
Hmm. I think we are talking about two separate issues here:
- sorting by type of official
- box height varies because the description for some types of officials are longer

I would like to deal with the sorting in a separate issue. It's a bit tricky.

As far as the box height, it definitely needs to be dealt with somehow. @acacheung, what do you think?

**Comment by acacheung** [comment]
@walter I'm not sure how this people list is getting rendered. It should have equal height li's, but what I think is happening is that the javascript is running before the list is getting loaded in. We can chat about this later if you have time.

**Comment by walter** [comment]
Code in question is here:

https://github.com/opengovernment/opengovernment-app/blob/master/app/assets/javascripts/questions.js.coffee#L117-L164

**Comment by walter** [comment]
Closing this now that #121 is open to handle sorting by office held.
