### ISSUE TITLE
allow elected officials to register a verified account

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#18]
Issue for 7(a) on dev roadmap. 

On splash page, an elected official can input her email address and select that she's an elected official. Site admins can then manually verify her email address is official gov't one, and activate her as a class of user that can answer questions addressed to her. 

As we discussed, in the future we may build an administrative dashboard page of all questions to a verified user - but not nec. for launch.

**Comment by walter** [comment]
Thinking through the technical design here:
- we base sign up on that of normal users (including email confirmation for sign up), with some additions
- a user that is a candidate for becoming a "verified" recipient has a person_id that associates the user's account with the corresponding person record
- we take the user's signed up email and check it against emails we have for people and use that to match the right person_id for the user
- since emails can be intercepted, etc. the user isn't completely verified as matching the person until a site staff member has manually (called the office of the person or the like) confirmed that person has indeed registered as a user
- we send an email notification to staff that a user has requested to be verified
- the site staff member marks the user account as being verified as the person

There are couple areas in this that we may improve in the future:
- if we don't find a matching email, allow the user to find matching person via office and name perhaps
- automate more of the verification process that will fall on staff members for now

**Comment by walter** [comment]
I need some insight on how to handle this "from the splash page".

Currently this works from the standard sign up page. If a person enters an email address while signing up, we ask them if they are the person that matches and then that is submitted to a staff member to verify.

But that is from the standard, full, sign up page. @davidmooreppf, is that sufficient for the moment?

If not, I'm not sure if we can use the current "splash" page for this as it is tied to the CRM, etc. What are our options?

**Comment by davidmooreppf** [comment]
As in IRC chat, it's fine for splash page to just go into CRM, and not into production DB on AskThem app. We'll either mail them a /register link when it's time to show the production site preview, or add them manually.

**Comment by walter** [comment]
Cool. Read IRC about it. Closing this than.
