### ISSUE TITLE
on homepage, different UI for searching by location

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#185]
On homepage City, State or Zip search box :: http://preview.askthem.io

... a new visitor may not know she has to click the magnifying glass to activate the search. 

Would you advise a little "go" button, or a "enter" button instead of the magnifying glass?

**Comment by kidfribble** [comment]
These sorts of things can go a huge number of ways, but the truth is that you won't know for sure unless you test it. 

I've implemented several magnifying glass icon submit buttons that users grasped, but it doesn't mean it's right here. I don't know if it's in the budget, but you might want to use http://www.usertesting.com/ and have people figure out how to "search for a question".

Contextually, that icon doesn't make sense (it could be a pin instead), and it's not clear why you should enter in any information at all with the only title being "Get answers from elected officials & support questions by your fellow citizens!". I suggest adding something like "Find discussions near you" (not perfect) and replacing the icon with a pin instead of changing the look of this. Two buttons right here would really dilute the message and reduce the effectiveness of the page.

**Comment by davidmooreppf** [comment]
OK good to weigh. Thanks Steve.
