### ISSUE TITLE
threshold bar design enhancements

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#233]
The threshold bar seems a bit flat & plain. More gov't info display than challenge to visitors to sign & share & reach. 

We don't have bandwidth to do five designs and test two of them, but what would it look like to make the sign-on panel on Q pages more exciting? 

We could have a "delivery" icon at the right-hand end? Or the word "Delivered" or "Delivery!", but that's obvs. wordy. 

Or a question mark that fills up vertically as it's signed? 

Or darker outline around the progress bar and another eye-catching design tweak? 

http://preview.askthem.io/ri/questions/52b231f39d29c9439c000002

... realize this is cheesy, but want to get your thoughts. @walter ?

**Comment by walter** [comment]
There are a number of issues around the language of signatures for a question. You sign a petition, but to me, you support a question. We also use "sign in" which also conflicts.

I think we run with what we have and identify it as an overall area we want examine in the UX, but after launch instead of a rush job now.

Resist the urge to over tinker before we can measure what works and what doesn't with real users.

**Comment by davidmooreppf** [comment]
We don't do enough to signal what the goal of getting more signatures is on each Q page, which I haven't focused on enough until now. 

Amanda, do we have time today to try design for signaling it reaches "Delivery >>" ? A vertical line at the end of the bar, with the word "delivery" in gray above the bar on the right? 

If we don't, it'll have to wait. 

And yes, we'll test, for sure.

**Comment by davidmooreppf** [comment]
If "delivery" is too heavy-handed as an image, disregard. 

The bar seems pretty thin - could it be thicker? 

But let's please try to put "194 signatures" above the bar to the left, and "6 signatures needed" below the bar to the right. I.e. number of signers above, number needed below.
