### ISSUE TITLE
update README with Mongo and Redis requirements & instructions

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#31]
Both mongod and redis-server must be running for the app to function properly. This should be reflected in the README. 

@walter shall I go ahead and add?

**Comment by walter** [comment]
Sounds good.

**Comment by walter** [comment]
Oh, I should do that in the emoji style!

:+1:

**Comment by derekeder** [comment]
:ok_hand:

**Comment by walter** [comment]
@evz covered this with [this commit](https://github.com/opengovernment/opengovernment-app/commit/05fe61b7dea50ac114a3ce3ed749a5acc093a1cf), correct?

Or is there more to do? If not, go ahead and close this, please.

P.S. - Now that we are using github issues, we should try to include references to them in our commit messages (e.g. #31 in a commit message would like back to this issue).

Worth having a read of these to posts on commit messages if you haven't before:

http://robots.thoughtbot.com/post/48933156625/5-useful-tips-for-a-better-commit-message

http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

I really should put together a contributors.md at some point...

**Comment by evz** [comment]
My intent on that commit was to make sure that all the OS level requirements were listed. Those are the ones that I had to install when I was setting this up on a totally bare Ubuntu VM. I guess if you install redis and mongodb from your OS's package manager, it's implied that they will be running and this app does expect them to be running on the default ports but it would be nice to actually explicitly state that they should be running in that default way in order for the app to work properly. And maybe describe how to change the configuration within the app if you want them to run in a non-default way.

@derekeder Does that sound sane? If so, I'll try to get to that maybe Monday evening (which is, I suppose, sometime Tuesday morning for @walter).

**Comment by walter** [comment]
Hmm. I'm hesitant to spend much effort in the README on reproducing installation steps that perhaps are better described by the required softwares' own project installation guides or even the user's own preferences.

For example I use rbenv rather than rvm. The important information is that Ruby 1.9.3 is required.

These steps evolve over time and we don't want to spend very much effort in keeping them up-to-date.

My preference is for the following:
- describe our expectations for required software we need, i.e. a Dependencies (or Requirements) section that states Redis and MongoDB on default ports, etc.
- a "here's what installation steps may look like" link to a gist that covers installation on a given platform if we have it

This is pretty much the approach what RailsCasts does for tutorials when they require an external dependency. E.g. here's the requirement, here's how I did it on OS X with homebrew at the time of writing.

I do appreciate you updating things as you encounter missing steps.

**Comment by derekeder** [comment]
Agreed we shouldn't get too specific on OS specific requirements. The commit by @evz (05fe61b7) handles this well enough for other developers to dive in. We can swing back around and refine the Readme on launch.
