### ISSUE TITLE
QA on emails when signing a question - images & report links

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#327]
Tester reminds us ::

Minor bugs to report: your logo isn't making it through on emails, and neither the "Didn't support this question?" nor the "unsubscribe" links actually have a target URL.

---------- Forwarded message ----------
From: AskThem.io - Support support@askthem.io
Date: Fri, Feb 7, 2014 at 4:02 PM
Subject: You're Signed On to 'What is the appropriate reach of U.S. national security?'

I'll test again, cc @walter

**Comment by walter** [comment]
Essentially a duplicate of #326. Closing that one.

**Comment by walter** [comment]
Links fixed.

The image problem appears to be Gmail client specific. 

Background:

https://support.google.com/mail/answer/145919?p=display_images&rd=1

People having similar problems:

https://productforums.google.com/forum/#!topicsearchin/gmail/image$20not$20showing%7Csort:relevance%7Cspell:true/gmail/q47KoUYQXPw

Possible solution:

https://support.google.com/a/answer/3299041?hl=en

In the end I believe the issue is probably that we are using .svg for our logo rather than gif or png. Will investigate if that fixes it.

**Comment by walter** [comment]
Switching to png version of logo solved the problem in 02ea16e.

Note for #326.
