### ISSUE TITLE
didn't receive confirmation email when creating a new account

### ISSUE THREAD

**Issue by derekeder** [opengovernment/askthem-legacy#33]
Steps to reproduce:
- Navigated to sign up page: http://oglocal.herokuapp.com/users/sign_up
- filled out form
- automatically signed in to site, but never got a confirmation email
- after logout, unable to sign back in because account is not confirmed

[Confirmable](http://rubydoc.info/github/plataformatec/devise/master/Devise/Models/Confirmable) seems to be set in user model for devise. Is email sending not yet active on production? If so, [this ops issue](https://github.com/opengovernment/ops/issues/10) should be prioritized first

**Comment by walter** [comment]
Since "production" is really a staging site where we are testing at this point, we're using the mailtrap add-on for Heroku.

Basically it means that any outgoing email from the staging site is "trapped" instead of sent. I'll get you the details on how to view the trapped emails. If that satisfies this issue, please close it.

**Comment by derekeder** [comment]
Yes, sounds good. Important to have since #16 #19 and #23 all require testing emails
