### ISSUE TITLE
support hyperlinks in future official question response

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#399]
Re: closed #359, currently verified-account answers (as tested on Brad Lander's profile) don't support hyperlinks anymore. 

Link-shorteners are fine for now, to make sure that longer links don't bleed out of the response box, but in the future, hyperlinks in HTML for responders will be nice.

**Comment by walter** [comment]
See #396. We support links, as simply URL in the content, already, but some are bleeding over and it doesn't seem to be just about length.

If you have an example of how this is failing, it would be useful to try and recreate it on staging so I can look into the circumstances.

**Comment by walter** [comment]
Judging by the answer here, what you are actually referring to is HTML hyperlinking via anchor tags or something like Markdown syntax like what we use Github.

I.e. it's not a problem of the URLs being linked overflowing, but one where you would like words to be a hyperlink rather than the URL.

Right now we use an add-on called auto_html for this functionality (URL linking). I'll look into whether it has a plugin for handling anchor tags.

**Comment by davidmooreppf** [comment]
Yep that's what I meant to follow-up with. If not a href=", then using markdown syntax or whatever is fine too. Don't really care. 

http://daringfireball.net/projects/markdown/syntax#link
