### ISSUE TITLE
display of city council agendas & minutes off city overview pages

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#57]
Placeholder for minimum info display - give users access to council meetings & agendas on a city overview page. 

Two menu items up top somewhere. Goes to list of browsable meetings, in whatever .pdf viewing solution we decide. Includes comments. 

Down the road, a great goal would be to display questions about an individ. agenda, but that's not MVP.

To be refined for @walter & @derekeder w/r/t specific content for Philadelphia.

**Comment by walter** [comment]
@davidmooreppf any more thoughts on this or are we ready to hand this off to @derekeder for implementation?

**Comment by derekeder** [comment]
@davidmooreppf & @walter taking a look at this, but before we dive in it would be good to get some details on the city page:

![screen shot 2013-08-30 at 12 08 25 pm](https://f.cloud.github.com/assets/919583/1059236/d3a4092e-1196-11e3-8e9f-9b125107e69a.png)

First off, should this say the city name instead of just 'City'? In PA, folks in Pittsburgh might feel left out ...

Second, do we want an overview page similar to the state overview? 

![screen shot 2013-08-30 at 12 07 00 pm](https://f.cloud.github.com/assets/919583/1059261/2adb69e4-1197-11e3-8a0a-a09684bd3929.png)

We could list the city council members (we have this [list from Legistar](http://phila.legistar.com/People.aspx), but is there a better source?) on one tab, and the meeting agendas on another.

**Comment by walter** [comment]
> First off, should this say the city name instead of just 'City'? In PA, folks in Pittsburgh might feel left out ...

I would say that "City" should probably be a drop down menu (not my favorite widget, but logical in this context) with available city links.

> Second, do we want an overview page similar to the state overview?

Take a look at http://oglocal.herokuapp.com/pa-philadelphia and http://oglocal.herokuapp.com/ca-san-jose/.

These are how we are currently handling cities. Long term there will likely be some tweaks (Mayors display added, council members will probably become instances of CouncilMember rather than just Person), but you can get the idea.

In my view Bills and Key Votes (which I don't think we will have at launch) could replaced with Meeting Agendas and  Meeting Minutes or perhaps just "Meetings".

@davidmooreppf what do you think?

**Comment by walter** [comment]
@derekeder for development using these cities at this stage it's tricky to get the data. I'll see what I can hand off to you. Will be in touch.

**Comment by walter** [comment]
One thing that has been discussed is whether we want an embedded PDF reader for our agendas/minutes. Here's a tool that might come in useful for that:

https://github.com/mozilla/pdf.js
