### ISSUE TITLE
on question detail page, boxes below fold 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#75]
On a question page, re: http://oglocal.herokuapp.com/ny/questions/5217e34567c4052791000004

... below question body, show Disqus comments.

... then, display link to login as verified user to answer. Depends on this part. @walter

**Comment by walter** [comment]
Talked about in #72, if closed there, close this. If other things are holding that up, @acacheung feel free to tackle this and manage the work in this issue.

**Comment by walter** [comment]
Unfortunately couldn't get this sorted in #72. @acacheung if you can take a crack at this now that #72 is merged to master, that would be great. Thanks.

**Comment by walter** [comment]
I investigated a bit and it looks like this is width issue.

If I dial this line's width value down, then the sign up box sucks back up to the top and right:

https://github.com/opengovernment/opengovernment-app/blob/master/app/assets/stylesheets/modules/questions.sass#L223

In addition, you can slim the padding for div.actions here:

https://github.com/opengovernment/opengovernment-app/blob/master/app/assets/stylesheets/modules/questions.sass#L388

I didn't commit any changes because I couldn't get a mix that didn't look out of sort with the large margins/padding in that horizontal layout. I'm not sure where to tweak those. Leaving this for @acacheung to handle on Monday.

**Comment by walter** [comment]
@acacheung this one is a priority.

**Comment by acacheung** [comment]
@walter Can we chat about this? My local version doesn't match oglocal
