### ISSUE TITLE
tweaks to second page of /questions/new

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#9]
On second page, e.g. ::

http://cl.ly/image/3O2t0V1B0l0j

... the field lengths don't quite seem inviting. 

Should the Summary field be a speech bubble, like a comic? Too cute? 

Should Full Question field be default to display three full blank lines in the box, to show that the goal is to add more copy there than in the summary? Feels somehow crowded or restricted. Realize I could be more helpful here. 

I'll take a stab at refining the help copy on right-hand side, viz. for diff. levels of gov't. Will be shorter.

**Comment by kidfribble** [comment]
Yeah, we used to have those fields as multiple flat lines (instead of basic input visuals) but saw the possibility of it becoming too confusing, especially when there are underlines dividing the headers from form content. I think we need to spend a little time back in photoshop to give the flow a fresh work through.

**Comment by kidfribble** [comment]
![address_lookup_1b](https://f.cloud.github.com/assets/241320/857664/b0285038-f556-11e2-895c-b0a1acb39918.jpg)

Looking at doing this for all stages of the questions flow. I'll probably copy the same layout for signing up. In order to provide greater focus on the tasks ahead of the user, I removed everything the user wouldn't need if they decided to ask a question (or signup/sign in). Interested in your thoughts on this @walter.

**Comment by kidfribble** [comment]
To make this layout possible, @walter, I think I'll need to create a new layout template. I'm not sure how those templates are properly called, I thought it was a routes.rb thing but it appears to be void of anything layout related. Any suggestions?

**Comment by walter** [comment]
@kidfribble app/views/layouts/application.html.erb is the site wide default layout.

You can use a different layout specifically in a controller... however in this case, I might just alter app/views/questions/new.html.erb as all the partials are surrounded by it.

**Comment by kidfribble** [comment]
In order to use the same template I would need to have a body class or something to hide all the extra stuff I don't need, or just make a new template for this case, which I think is right. As it stands now (working inside of app/views/questions/new.html.erb) I can only edit what's in the white block: http://db.tt/juf0NOjg

**Comment by kidfribble** [comment]
Sorry, having a bit of trouble remembering how Ruby controllers link to layouts! :(
I assume we'd put something like "layout: _layout_file_name_" in here somewhere:

```
 def new
    layout: file_name
    #all other def stuffs
 end
```

**Comment by walter** [comment]
Out at breakfast at the moment, but you  should be able to find it in here:

http://guides.rubyonrails.org/layouts_and_rendering.html

**Comment by kidfribble** [comment]
Awesome, thanks! Enjoy breakfast :)

**Comment by kidfribble** [comment]
Got it with some help here. I was hitting some weird error and had placed my render in the wrong position. I also had a double render error which was solved by commenting out the "new!" at the bottom of the "new" method in questions_controller.rb

**Comment by walter** [comment]
Yeah, [Inherited Resources](https://github.com/josevalim/inherited_resources) add a little twist to the controller.
