### ISSUE TITLE
on Government tab, display of exec. branch info. after legislature

### ISSUE THREAD

**Issue by davidmooreppf** [opengovernment/askthem-legacy#90]
Let's display legislators first, on the left. Upper & lower chambers. Then, to the right:

On fed. Government tab, have a box for exec branch: Obama & Biden et al. Will get their data from Democracy Map. 

On state gov't, have a box for exect branch: governor. (THat might be sufficient, via D-Map.) 

On city gov't, have a box for exec branch where applicable: mayor or other. Via D-Map & local data sources.

**Comment by walter** [comment]
@acacheung would be great if you could mock this up with static HTML. I would probably put aside Mayor for now as I can adjust what you do to suit that situation.

@davidmooreppf is point person for what this should look like.

**Comment by davidmooreppf** [comment]
Not much brilliant to add here. So on a Government page, e.g. :: http://oglocal.herokuapp.com/ny

... strip out bills & key votes. 

The exec. chamber box in the horizontal row up top should be the same as the legislature boxes, of course. 

For a placeholder, it can just read "Governor". It doesn't need to say "1 Governor". 

Until Walter hooks up the exec branch data, Amanda, the placeholder for when a visitor clicks on that tab can just be two generic elected officials. One will be Governor and the other will be Attorney General (those are both offered by Democracy Map in NY state, at least, we'll see about other states I guessed).

**Comment by walter** [comment]
I'm still concerned about the overall design of the horizontal boxes.

It seems like we need to adjust the design to better handle things:
- the height needs to handle more parties, see http://oglocal.herokuapp.com/vt, the uneven height is weird to me
- the number of boxes -- can we basically have it so that the boxes stretch to take up all the horizontal space (as it did when there were 4)

Thoughts?

**Comment by walter** [comment]
Following up on the height issue, looking at Vermont's list of distinct parties for representatives, I see that there are two more additional parties that look to be cut off; Progressive, Independent.

Update: the "cut off" might be a query issue rather than styling, but the point remains that height for states with more than two parties is problematic.
